[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.18"

[fmt]
line_length = 100
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${ARCHIVE_NODE_URL_L2}"
optimismGoerli = "${ARCHIVE_NODE_URL_GOERLI_L2}"

[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY}" }
optimismGoerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config